spring:
  # db 설정
  datasource:
#    hikari:
#      driver-class-name: com.mysql.jdbc.Driver
#      jdbc-url: jdbc:mysql://localhost:3306/market_consumer?serverTimezone=UTC&characterEncoding=UTF-8
#      username: root
#      password: dksthddl
    url: jdbc:mysql://localhost:3306/market_consumer?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: dksthddl

  # jpa 설정
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate :
#        format_sql : true
#    database: mysql

  # mail 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
app:
  host: http://localhost:8084
server:
  port: 8085
