spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: AIzaSyBTx7iNUsUsnXdMkTPRaB8XHJUiVIRINy4
            client-secret: epkv9tXwvUOZAUIDHALNfrhQ
            scope:
              - profile
              - email
          kakao:
            authorization-grant-type: authorization_code
            client-id: e28905f1714ccc3b412c96305c0a995f
            client-secret: b3l2ka7dYJc1uLow0oyskLdmy8l6H36b
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            redirect-uri: "http://localhost:8086/login/oauth2/code/kakao"
            scope:
              - profile
            client-authentication-method: POST
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
