spring:
  # db 설정
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/market?serverTimezone=UTC&characterEncoding=UTF-8
      username: market
      password: market
    username: market
    password: market
    url: jdbc:mysql://localhost:3306/market?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver

  # jpa 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate :
        format_sql : true
    database: mysql
  profiles:
    include: oauth
app:
  host: http://localhost:8084
server:
  port: 8086
email:
  admin:
    account: certification0test@gmail.com
    password: PCMmanager!