spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 756788687308-mb5d6qacs350410a7qg04ae74oekc2vh.apps.googleusercontent.com
            client-secret: epkv9tXwvUOZAUIDHALNfrhQ
            scope:
              - profile
              - email
          kakao:
            authorization-grant-type: authorization_code
            client-id: 700d5a1ccfd740ee923796e42c90eba4
            client-secret: x5BzOQ8EcwFq3LRW9j8te899g4WVTDYa
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile
            client-authentication-method: POST
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
