# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build Shop
      run: ./gradlew bootJar -p ./market-shop 
    - name: Build user
      run: ./gradlew bootJar -p ./market-user
    - name: Build common
      run: ./gradlew bootJar -p ./market-common
    - name: Build order
      run: ./gradlew bootJar -p ./market-order
    - name: Build product
      run: ./gradlew bootJar -p ./market-product
    - name: Build search
      run: ./gradlew bootJar -p ./market-search
